"""add_completed_orders_to_customer

Revision ID: 07ed3c1fe158
Revises: 7804dd25eb88
Create Date: 2026-01-11 10:52:28.622939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07ed3c1fe158'
down_revision: Union[str, None] = '7804dd25eb88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('completed_orders', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'completed_orders')
    # ### end Alembic commands ###
