"""add_top_refunded_products

Revision ID: 16af294f87f4
Revises: 1cd688dae1d7
Create Date: 2025-12-24 11:55:47.777485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16af294f87f4'
down_revision: Union[str, None] = '1cd688dae1d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_analytics', sa.Column('top_refunded_products', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('daily_stats', sa.Column('top_refunded_products', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_stats', 'top_refunded_products')
    op.drop_column('daily_analytics', 'top_refunded_products')
    # ### end Alembic commands ###
