"""add_provisional_revenue

Revision ID: 1ae3a4678d66
Revises: c651b0bed976
Create Date: 2025-12-17 09:47:33.060216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae3a4678d66'
down_revision: Union[str, None] = 'c651b0bed976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_analytics', sa.Column('provisional_revenue', sa.Float(), nullable=True))
    op.add_column('daily_stats', sa.Column('provisional_revenue', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_stats', 'provisional_revenue')
    op.drop_column('daily_analytics', 'provisional_revenue')
    # ### end Alembic commands ###
