"""add_financial_events_to_daily_analytics

Revision ID: 1cd688dae1d7
Revises: 1ae3a4678d66
Create Date: 2025-12-17 11:58:02.888901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cd688dae1d7'
down_revision: Union[str, None] = '1ae3a4678d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_analytics', sa.Column('financial_events', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_analytics', 'financial_events')
    # ### end Alembic commands ###
