"""change_order_refund_to_string

Revision ID: 22dabc5cc5ac
Revises: a1b80ab261d1
Create Date: 2026-01-29 17:28:10.642678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22dabc5cc5ac'
down_revision: Union[str, None] = 'a1b80ab261d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('revenues', 'order_refund',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_revenues_order_refund'), 'revenues', ['order_refund'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revenues_order_refund'), table_name='revenues')
    op.alter_column('revenues', 'order_refund',
               existing_type=sa.String(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
