"""replace_return_count_with_profit

Revision ID: 23b58976feb9
Revises: 4f51a964a0ff
Create Date: 2026-01-28 06:05:07.499352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23b58976feb9'
down_revision: Union[str, None] = '4f51a964a0ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('profit', sa.Float(), nullable=True))
    op.drop_column('customers', 'return_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('return_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('customers', 'profit')
    # ### end Alembic commands ###
