"""add_import_logs_table

Revision ID: 2b6ccc44546b
Revises: remove_provisional_col
Create Date: 2026-01-25 07:28:41.903584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b6ccc44546b'
down_revision: Union[str, None] = 'remove_provisional_col'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('log', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_logs_brand_id'), 'import_logs', ['brand_id'], unique=False)
    op.create_index(op.f('ix_import_logs_file_hash'), 'import_logs', ['file_hash'], unique=False)
    op.create_index(op.f('ix_import_logs_id'), 'import_logs', ['id'], unique=False)
    op.create_index(op.f('ix_import_logs_source'), 'import_logs', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_logs_source'), table_name='import_logs')
    op.drop_index(op.f('ix_import_logs_id'), table_name='import_logs')
    op.drop_index(op.f('ix_import_logs_file_hash'), table_name='import_logs')
    op.drop_index(op.f('ix_import_logs_brand_id'), table_name='import_logs')
    op.drop_table('import_logs')
    # ### end Alembic commands ###
