"""Add full marketing KPIs to DailyStat table

Revision ID: 38cc074603cc
Revises: 87bb56ee2838
Create Date: 2025-11-24 07:25:41.536299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38cc074603cc'
down_revision: Union[str, None] = '87bb56ee2838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_stats', sa.Column('cpm', sa.Float(), nullable=True))
    op.add_column('daily_stats', sa.Column('cpa', sa.Float(), nullable=True))
    op.add_column('daily_stats', sa.Column('ctr', sa.Float(), nullable=True))
    op.add_column('daily_stats', sa.Column('cpc', sa.Float(), nullable=True))
    op.add_column('daily_stats', sa.Column('conversions', sa.Integer(), nullable=True))
    op.add_column('daily_stats', sa.Column('impressions', sa.Integer(), nullable=True))
    op.add_column('daily_stats', sa.Column('clicks', sa.Integer(), nullable=True))
    op.add_column('daily_stats', sa.Column('reach', sa.Integer(), nullable=True))
    op.add_column('daily_stats', sa.Column('frequency', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_stats', 'frequency')
    op.drop_column('daily_stats', 'reach')
    op.drop_column('daily_stats', 'clicks')
    op.drop_column('daily_stats', 'impressions')
    op.drop_column('daily_stats', 'conversions')
    op.drop_column('daily_stats', 'cpc')
    op.drop_column('daily_stats', 'ctr')
    op.drop_column('daily_stats', 'cpa')
    op.drop_column('daily_stats', 'cpm')
    # ### end Alembic commands ###
