"""remove_unused_customer_columns

Revision ID: 4f51a964a0ff
Revises: 660828c72e1d
Create Date: 2026-01-27 09:44:56.690024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f51a964a0ff'
down_revision: Union[str, None] = '660828c72e1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('source', sa.String(), nullable=True))
    op.drop_index('ix_customers_order_id', table_name='customers')
    op.drop_index('ix_customers_source_id', table_name='customers')
    op.drop_index('ix_customers_tracking_id', table_name='customers')
    op.create_index(op.f('ix_customers_source'), 'customers', ['source'], unique=False)
    op.drop_constraint('customers_order_id_fkey', 'customers', type_='foreignkey')
    op.drop_column('customers', 'tracking_id')
    op.drop_column('customers', 'updated_at')
    op.drop_column('customers', 'source_id')
    op.drop_column('customers', 'created_at')
    op.drop_column('customers', 'last_order_date')
    op.drop_column('customers', 'order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('last_order_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('source_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('tracking_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('customers_order_id_fkey', 'customers', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_customers_source'), table_name='customers')
    op.create_index('ix_customers_tracking_id', 'customers', ['tracking_id'], unique=False)
    op.create_index('ix_customers_source_id', 'customers', ['source_id'], unique=False)
    op.create_index('ix_customers_order_id', 'customers', ['order_id'], unique=False)
    op.drop_column('customers', 'source')
    # ### end Alembic commands ###
