"""add order_date to revenues

Revision ID: 5673a58d564e
Revises: 8b1aa252524e
Create Date: 2025-12-07 07:42:31.501503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5673a58d564e'
down_revision: Union[str, None] = '8b1aa252524e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revenues', sa.Column('order_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revenues', 'order_date')
    # ### end Alembic commands ###
