"""change_user_id_to_string_and_add_owner_id_to_brand

Revision ID: 5d404cc86aed
Revises: f7fefea9934e
Create Date: 2026-02-26 09:57:13.911184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d404cc86aed'
down_revision: Union[str, None] = 'f7fefea9934e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Alter users.id first (with explicit cast for Postgres)
    op.execute('ALTER TABLE users ALTER COLUMN id TYPE VARCHAR(255) USING id::text')
    
    # 2. Then add column to brands
    op.add_column('brands', sa.Column('owner_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_brands_owner_id'), 'brands', ['owner_id'], unique=False)
    
    # 3. Finally create foreign key
    op.create_foreign_key(None, 'brands', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'brands', type_='foreignkey')
    op.drop_index(op.f('ix_brands_owner_id'), table_name='brands')
    op.drop_column('brands', 'owner_id')
    # ### end Alembic commands ###
