"""add_json_cols_to_dailystat

Revision ID: 5d5f116308d7
Revises: 7281dd270f10
Create Date: 2025-11-28 10:14:17.664065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d5f116308d7'
down_revision: Union[str, None] = '7281dd270f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_stats', sa.Column('hourly_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('daily_stats', sa.Column('payment_method_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('daily_stats', sa.Column('cancel_reason_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('daily_stats', sa.Column('location_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('daily_stats', sa.Column('top_products', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_stats', 'top_products')
    op.drop_column('daily_stats', 'location_distribution')
    op.drop_column('daily_stats', 'cancel_reason_breakdown')
    op.drop_column('daily_stats', 'payment_method_breakdown')
    op.drop_column('daily_stats', 'hourly_breakdown')
    # ### end Alembic commands ###
