"""add_new_fields_to_customer

Revision ID: 612e62744943
Revises: d2e1c7ba3fa7
Create Date: 2026-01-26 09:48:29.410470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612e62744943'
down_revision: Union[str, None] = 'd2e1c7ba3fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('username', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('tracking_id', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_customers_order_id'), 'customers', ['order_id'], unique=False)
    op.create_index(op.f('ix_customers_tracking_id'), 'customers', ['tracking_id'], unique=False)
    op.create_index(op.f('ix_customers_username'), 'customers', ['username'], unique=False)
    op.create_foreign_key(None, 'customers', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_username'), table_name='customers')
    op.drop_index(op.f('ix_customers_tracking_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_order_id'), table_name='customers')
    op.drop_column('customers', 'order_id')
    op.drop_column('customers', 'tracking_id')
    op.drop_column('customers', 'username')
    # ### end Alembic commands ###
