"""update customer order_id fk to cascade

Revision ID: 660828c72e1d
Revises: cda1f50b8076
Create Date: 2026-01-27 08:27:46.558578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '660828c72e1d'
down_revision: Union[str, None] = 'cda1f50b8076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customers_order_id_fkey', 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key('customers_order_id_fkey', 'customers', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
