"""add_delivered_date_and_customer_source

Revision ID: 7281dd270f10
Revises: 8de625ea442f
Create Date: 2025-11-28 08:14:03.000678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7281dd270f10'
down_revision: Union[str, None] = '8de625ea442f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('source', sa.String(), nullable=True))
    op.create_index(op.f('ix_customers_source'), 'customers', ['source'], unique=False)
    op.add_column('orders', sa.Column('delivered_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivered_date')
    op.drop_index(op.f('ix_customers_source'), table_name='customers')
    op.drop_column('customers', 'source')
    # ### end Alembic commands ###
