"""add operational columns to dailystat

Revision ID: 74430360a2c4
Revises: 9e5fcae134c2
Create Date: 2025-11-19 16:20:08.218870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74430360a2c4'
down_revision: Union[str, None] = '9e5fcae134c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_stats', sa.Column('cancelled_orders', sa.Integer(), nullable=True))
    op.add_column('daily_stats', sa.Column('refunded_orders', sa.Integer(), nullable=True))
    op.add_column('daily_stats', sa.Column('completed_orders', sa.Integer(), nullable=True))
    op.add_column('daily_stats', sa.Column('total_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_stats', 'total_quantity')
    op.drop_column('daily_stats', 'completed_orders')
    op.drop_column('daily_stats', 'refunded_orders')
    op.drop_column('daily_stats', 'cancelled_orders')
    # ### end Alembic commands ###
