"""add_customer_order_analytics_table

Revision ID: 74ce022fd3b8
Revises: 07ed3c1fe158
Create Date: 2026-01-14 06:35:53.896508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74ce022fd3b8'
down_revision: Union[str, None] = '07ed3c1fe158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_order_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('order_code', sa.String(), nullable=True),
    sa.Column('tracking_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('shipping_address', sa.String(), nullable=True),
    sa.Column('product_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.Column('is_bomb', sa.Boolean(), nullable=True),
    sa.Column('is_refunded', sa.Boolean(), nullable=True),
    sa.Column('full_search_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'order_code', name='uq_analytics_order_code')
    )
    op.create_index(op.f('ix_customer_order_analytics_brand_id'), 'customer_order_analytics', ['brand_id'], unique=False)
    op.create_index(op.f('ix_customer_order_analytics_id'), 'customer_order_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_customer_order_analytics_order_code'), 'customer_order_analytics', ['order_code'], unique=False)
    op.create_index(op.f('ix_customer_order_analytics_order_date'), 'customer_order_analytics', ['order_date'], unique=False)
    op.create_index(op.f('ix_customer_order_analytics_phone_number'), 'customer_order_analytics', ['phone_number'], unique=False)
    op.create_index(op.f('ix_customer_order_analytics_source'), 'customer_order_analytics', ['source'], unique=False)
    op.create_index(op.f('ix_customer_order_analytics_status'), 'customer_order_analytics', ['status'], unique=False)
    op.create_index(op.f('ix_customer_order_analytics_tracking_id'), 'customer_order_analytics', ['tracking_id'], unique=False)
    op.create_index(op.f('ix_customer_order_analytics_username'), 'customer_order_analytics', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_order_analytics_username'), table_name='customer_order_analytics')
    op.drop_index(op.f('ix_customer_order_analytics_tracking_id'), table_name='customer_order_analytics')
    op.drop_index(op.f('ix_customer_order_analytics_status'), table_name='customer_order_analytics')
    op.drop_index(op.f('ix_customer_order_analytics_source'), table_name='customer_order_analytics')
    op.drop_index(op.f('ix_customer_order_analytics_phone_number'), table_name='customer_order_analytics')
    op.drop_index(op.f('ix_customer_order_analytics_order_date'), table_name='customer_order_analytics')
    op.drop_index(op.f('ix_customer_order_analytics_order_code'), table_name='customer_order_analytics')
    op.drop_index(op.f('ix_customer_order_analytics_id'), table_name='customer_order_analytics')
    op.drop_index(op.f('ix_customer_order_analytics_brand_id'), table_name='customer_order_analytics')
    op.drop_table('customer_order_analytics')
    # ### end Alembic commands ###
