"""add_churn_rate

Revision ID: 77ecce1218f4
Revises: a1b2c3d4e5f6
Create Date: 2026-01-11 07:59:18.195313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ecce1218f4'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_analytics', sa.Column('churn_rate', sa.Float(), nullable=True))
    op.add_column('daily_stats', sa.Column('churn_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_stats', 'churn_rate')
    op.drop_column('daily_analytics', 'churn_rate')
    # ### end Alembic commands ###
