"""add_customer_aggregated_fields

Revision ID: 7804dd25eb88
Revises: 77ecce1218f4
Create Date: 2026-01-11 09:37:25.306416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7804dd25eb88'
down_revision: Union[str, None] = '77ecce1218f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('total_spent', sa.Float(), nullable=True))
    op.add_column('customers', sa.Column('total_orders', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('last_order_date', sa.DateTime(), nullable=True))
    op.add_column('customers', sa.Column('cancelled_orders', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('bomb_orders', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('refunded_orders', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'refunded_orders')
    op.drop_column('customers', 'bomb_orders')
    op.drop_column('customers', 'cancelled_orders')
    op.drop_column('customers', 'last_order_date')
    op.drop_column('customers', 'total_orders')
    op.drop_column('customers', 'total_spent')
    # ### end Alembic commands ###
