"""add_gin_indexes_for_order_and_revenue

Revision ID: 7e200e5a5beb
Revises: a2b3c4d5e6f7
Create Date: 2026-01-30 07:08:48.233060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e200e5a5beb'
down_revision: Union[str, None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_order_search_gin', 'orders', ['order_code', 'tracking_id', 'username'], unique=False, postgresql_using='gin', postgresql_ops={'order_code': 'gin_trgm_ops', 'tracking_id': 'gin_trgm_ops', 'username': 'gin_trgm_ops'})
    op.create_index('idx_revenue_search_gin', 'revenues', ['order_code', 'order_refund'], unique=False, postgresql_using='gin', postgresql_ops={'order_code': 'gin_trgm_ops', 'order_refund': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_revenue_search_gin', table_name='revenues', postgresql_using='gin', postgresql_ops={'order_code': 'gin_trgm_ops', 'order_refund': 'gin_trgm_ops'})
    op.drop_index('idx_order_search_gin', table_name='orders', postgresql_using='gin', postgresql_ops={'order_code': 'gin_trgm_ops', 'tracking_id': 'gin_trgm_ops', 'username': 'gin_trgm_ops'})
    # ### end Alembic commands ###
