"""add total_cost to daily_analytics

Revision ID: 7f56ac4fd444
Revises: 5d5f116308d7
Create Date: 2025-11-30 09:34:50.176463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f56ac4fd444'
down_revision: Union[str, None] = '5d5f116308d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_analytics', sa.Column('total_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_analytics', 'total_cost')
    # ### end Alembic commands ###
