"""add_bomb_orders

Revision ID: 8569ea8913a9
Revises: e484baad037e
Create Date: 2025-12-16 10:36:20.893163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8569ea8913a9'
down_revision: Union[str, None] = 'e484baad037e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_stats', sa.Column('bomb_orders', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('daily_stats', sa.Column('bomb_rate', sa.Float(), nullable=True, server_default='0.0'))
    op.add_column('daily_analytics', sa.Column('bomb_orders', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('daily_analytics', sa.Column('bomb_rate', sa.Float(), nullable=True, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_analytics', 'bomb_rate')
    op.drop_column('daily_analytics', 'bomb_orders')
    op.drop_column('daily_stats', 'bomb_rate')
    op.drop_column('daily_stats', 'bomb_orders')
    # ### end Alembic commands ###