"""drop ads table

Revision ID: 87bb56ee2838
Revises: bb71e3aa0365
Create Date: 2025-11-23 10:19:20.076677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87bb56ee2838'
down_revision: Union[str, None] = 'bb71e3aa0365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ad_brand_id_ad_date', table_name='ads')
    op.drop_index('ix_ads_brand_id', table_name='ads')
    op.drop_index('ix_ads_campaign_name', table_name='ads')
    op.drop_index('ix_ads_id', table_name='ads')
    op.drop_index('ix_ads_source', table_name='ads')
    op.drop_table('ads')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campaign_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ad_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('impressions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clicks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expense', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('orders', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gmv', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name='ads_brand_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ads_pkey')
    )
    op.create_index('ix_ads_source', 'ads', ['source'], unique=False)
    op.create_index('ix_ads_id', 'ads', ['id'], unique=False)
    op.create_index('ix_ads_campaign_name', 'ads', ['campaign_name'], unique=False)
    op.create_index('ix_ads_brand_id', 'ads', ['brand_id'], unique=False)
    op.create_index('ix_ad_brand_id_ad_date', 'ads', ['brand_id', 'ad_date'], unique=False)
    # ### end Alembic commands ###
