"""add total_quantity_sold to daily_analytics

Revision ID: 8b1aa252524e
Revises: 7f56ac4fd444
Create Date: 2025-12-07 03:10:31.447099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b1aa252524e'
down_revision: Union[str, None] = '7f56ac4fd444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_analytics', sa.Column('total_quantity_sold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_analytics', 'total_quantity_sold')
    # ### end Alembic commands ###
