"""add_cancel_reason_breakdown

Revision ID: 8de625ea442f
Revises: ccd441fdaa48
Create Date: 2025-11-27 03:57:10.271617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8de625ea442f'
down_revision: Union[str, None] = 'ccd441fdaa48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_analytics', sa.Column('cancel_reason_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_analytics', 'cancel_reason_breakdown')
    # ### end Alembic commands ###
