"""add_full_kpis_to_dailystat_table

Revision ID: 9bae518ca588
Revises: 74430360a2c4
Create Date: 2025-11-20 03:17:53.250443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bae518ca588'
down_revision: Union[str, None] = '74430360a2c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_stats', sa.Column('roi', sa.Float(), nullable=True))
    op.add_column('daily_stats', sa.Column('profit_margin', sa.Float(), nullable=True))
    op.add_column('daily_stats', sa.Column('take_rate', sa.Float(), nullable=True))
    op.add_column('daily_stats', sa.Column('aov', sa.Float(), nullable=True))
    op.add_column('daily_stats', sa.Column('upt', sa.Float(), nullable=True))
    op.add_column('daily_stats', sa.Column('completion_rate', sa.Float(), nullable=True))
    op.add_column('daily_stats', sa.Column('cancellation_rate', sa.Float(), nullable=True))
    op.add_column('daily_stats', sa.Column('refund_rate', sa.Float(), nullable=True))
    op.add_column('daily_stats', sa.Column('unique_skus_sold', sa.Integer(), nullable=True))
    op.add_column('daily_stats', sa.Column('total_quantity_sold', sa.Integer(), nullable=True))
    op.add_column('daily_stats', sa.Column('total_customers', sa.Integer(), nullable=True))
    op.drop_column('daily_stats', 'total_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_stats', sa.Column('total_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('daily_stats', 'total_customers')
    op.drop_column('daily_stats', 'total_quantity_sold')
    op.drop_column('daily_stats', 'unique_skus_sold')
    op.drop_column('daily_stats', 'refund_rate')
    op.drop_column('daily_stats', 'cancellation_rate')
    op.drop_column('daily_stats', 'completion_rate')
    op.drop_column('daily_stats', 'upt')
    op.drop_column('daily_stats', 'aov')
    op.drop_column('daily_stats', 'take_rate')
    op.drop_column('daily_stats', 'profit_margin')
    op.drop_column('daily_stats', 'roi')
    # ### end Alembic commands ###
