"""add customer segment distribution

Revision ID: 9d589de511ea
Revises: f1e7b13548a8
Create Date: 2026-01-07 08:56:25.647692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d589de511ea'
down_revision: Union[str, None] = 'ec9df125add9' # Fixed to match the actual latest revision in file structure if needed, but tool said 'ec9df125add9' was prev? 
# Wait, checking the list in prompt: 'f1e7b13548a8_add_new_returning_customers_to_dailystat.py' seems to be the latest based on folder list?
# The auto-generation said 'ec9df125add9'. Let's trust auto-generation for down_revision unless it's wrong.
# Folder list showed 'f1e7b13548a8'. 'ec9df125add9' is 'add_frequency_distribution'.
# 'f1e7b13548a8' seems newer. I should double check. 
# Actually, let's look at the file list again.
# ec9df125add9_add_frequency_distribution.py
# f1e7b13548a8_add_new_returning_customers_to_dailystat.py
# If alembic autogen picked ec9df125add9, maybe f1e7... wasn't applied or head?
# Safer to trust the file generated by alembic, but if I edit it, I should be careful.
# I will keep what alembic generated: 'ec9df125add9' IF that was indeed the parent. 
# BUT wait, the prompt file list shows f1e7b13548a8.
# Let me check the content of f1e7b13548a8 to see its down_revision.

branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add column to daily_stats
    op.add_column('daily_stats', sa.Column('customer_segment_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    # Add column to daily_analytics
    op.add_column('daily_analytics', sa.Column('customer_segment_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True))


def downgrade() -> None:
    op.drop_column('daily_analytics', 'customer_segment_distribution')
    op.drop_column('daily_stats', 'customer_segment_distribution')