"""scope_brand_uniqueness_to_owner

Revision ID: 9d5a48a9a512
Revises: 5d404cc86aed
Create Date: 2026-02-27 02:22:43.059720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d5a48a9a512'
down_revision: Union[str, None] = '5d404cc86aed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_brands_name', table_name='brands')
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=False)
    op.drop_index('ix_brands_slug', table_name='brands')
    op.create_index(op.f('ix_brands_slug'), 'brands', ['slug'], unique=False)
    op.create_unique_constraint('uq_brand_name_owner', 'brands', ['name', 'owner_id'])
    op.create_unique_constraint('uq_brand_slug_owner', 'brands', ['slug', 'owner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_brand_slug_owner', 'brands', type_='unique')
    op.drop_constraint('uq_brand_name_owner', 'brands', type_='unique')
    op.drop_index(op.f('ix_brands_slug'), table_name='brands')
    op.create_index('ix_brands_slug', 'brands', ['slug'], unique=True)
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.create_index('ix_brands_name', 'brands', ['name'], unique=True)
    # ### end Alembic commands ###
