"""Add cogs and execution_cost to DailyStat

Revision ID: 9e5fcae134c2
Revises: b18613eb1352
Create Date: 2025-11-19 09:44:33.341546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5fcae134c2'
down_revision: Union[str, None] = 'b18613eb1352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_stats', sa.Column('cogs', sa.Float(), nullable=True))
    op.add_column('daily_stats', sa.Column('execution_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_stats', 'execution_cost')
    op.drop_column('daily_stats', 'cogs')
    # ### end Alembic commands ###
