"""add_avg_repurchase_cycle

Revision ID: a1b2c3d4e5f6
Revises: f1e7b13548a8
Create Date: 2026-01-11 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '9d589de511ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_stats', sa.Column('avg_repurchase_cycle', sa.Float(), nullable=True, server_default='0.0'))
    op.add_column('daily_analytics', sa.Column('avg_repurchase_cycle', sa.Float(), nullable=True, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_analytics', 'avg_repurchase_cycle')
    op.drop_column('daily_stats', 'avg_repurchase_cycle')
    # ### end Alembic commands ###
