"""add_bomb_orders_to_customer

Revision ID: a1b80ab261d1
Revises: 23b58976feb9
Create Date: 2026-01-29 10:50:32.043749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b80ab261d1'
down_revision: Union[str, None] = '23b58976feb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('bomb_orders', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'bomb_orders')
    # ### end Alembic commands ###
