"""update_customer_schema_v3

Revision ID: a842e5721426
Revises: 612e62744943
Create Date: 2026-01-26 16:16:48.606834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a842e5721426'
down_revision: Union[str, None] = '612e62744943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('canceled_orders', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('refunded_orders', sa.Integer(), nullable=True))
    op.drop_column('customers', 'avatar_url')
    op.drop_column('customers', 'full_name')
    op.drop_column('customers', 'status')
    op.drop_column('customers', 'dob')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('customers', 'refunded_orders')
    op.drop_column('customers', 'canceled_orders')
    # ### end Alembic commands ###
