"""add marketing_spends table

Revision ID: bb71e3aa0365
Revises: 9bae518ca588
Create Date: 2025-11-23 09:07:39.214538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb71e3aa0365'
down_revision: Union[str, None] = '9bae518ca588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketing_spends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ad_spend', sa.Float(), nullable=True),
    sa.Column('cpm', sa.Float(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('cpa', sa.Float(), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'source', 'date', name='_brand_source_date_uc')
    )
    op.create_index(op.f('ix_marketing_spends_brand_id'), 'marketing_spends', ['brand_id'], unique=False)
    op.create_index(op.f('ix_marketing_spends_date'), 'marketing_spends', ['date'], unique=False)
    op.create_index(op.f('ix_marketing_spends_id'), 'marketing_spends', ['id'], unique=False)
    op.create_index(op.f('ix_marketing_spends_source'), 'marketing_spends', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketing_spends_source'), table_name='marketing_spends')
    op.drop_index(op.f('ix_marketing_spends_id'), table_name='marketing_spends')
    op.drop_index(op.f('ix_marketing_spends_date'), table_name='marketing_spends')
    op.drop_index(op.f('ix_marketing_spends_brand_id'), table_name='marketing_spends')
    op.drop_table('marketing_spends')
    # ### end Alembic commands ###
