"""add_gmv_selling_price_subsidy_to_orders

Revision ID: c651b0bed976
Revises: 8569ea8913a9
Create Date: 2025-12-17 09:31:00.389816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c651b0bed976'
down_revision: Union[str, None] = '8569ea8913a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('gmv', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('selling_price', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('subsidy_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'subsidy_amount')
    op.drop_column('orders', 'selling_price')
    op.drop_column('orders', 'gmv')
    # ### end Alembic commands ###
