"""update_order_date_to_datetime_and_add_daily_analytics

Revision ID: ccd441fdaa48
Revises: 38cc074603cc
Create Date: 2025-11-26 08:34:43.834868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccd441fdaa48'
down_revision: Union[str, None] = '38cc074603cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('gmv', sa.Float(), nullable=True),
    sa.Column('net_revenue', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('cogs', sa.Float(), nullable=True),
    sa.Column('execution_cost', sa.Float(), nullable=True),
    sa.Column('ad_spend', sa.Float(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('cpm', sa.Float(), nullable=True),
    sa.Column('cpa', sa.Float(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('completed_orders', sa.Integer(), nullable=True),
    sa.Column('cancelled_orders', sa.Integer(), nullable=True),
    sa.Column('refunded_orders', sa.Integer(), nullable=True),
    sa.Column('cancellation_rate', sa.Float(), nullable=True),
    sa.Column('refund_rate', sa.Float(), nullable=True),
    sa.Column('avg_fulfillment_time', sa.Float(), nullable=True),
    sa.Column('new_customers', sa.Integer(), nullable=True),
    sa.Column('returning_customers', sa.Integer(), nullable=True),
    sa.Column('new_customer_revenue', sa.Float(), nullable=True),
    sa.Column('returning_customer_revenue', sa.Float(), nullable=True),
    sa.Column('aov', sa.Float(), nullable=True),
    sa.Column('upt', sa.Float(), nullable=True),
    sa.Column('unique_skus_sold', sa.Integer(), nullable=True),
    sa.Column('hourly_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payment_method_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('location_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_products', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'date', 'source', name='uq_daily_analytics')
    )
    op.create_index(op.f('ix_daily_analytics_brand_id'), 'daily_analytics', ['brand_id'], unique=False)
    op.create_index(op.f('ix_daily_analytics_date'), 'daily_analytics', ['date'], unique=False)
    op.create_index(op.f('ix_daily_analytics_id'), 'daily_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_daily_analytics_source'), 'daily_analytics', ['source'], unique=False)
    op.alter_column('orders', 'order_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'order_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_index(op.f('ix_daily_analytics_source'), table_name='daily_analytics')
    op.drop_index(op.f('ix_daily_analytics_id'), table_name='daily_analytics')
    op.drop_index(op.f('ix_daily_analytics_date'), table_name='daily_analytics')
    op.drop_index(op.f('ix_daily_analytics_brand_id'), table_name='daily_analytics')
    op.drop_table('daily_analytics')
    # ### end Alembic commands ###
