"""add_order_refund_to_revenues

Revision ID: cda1f50b8076
Revises: a842e5721426
Create Date: 2026-01-27 07:28:18.065005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cda1f50b8076'
down_revision: Union[str, None] = 'a842e5721426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revenues', sa.Column('order_refund', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revenues', 'order_refund')
    # ### end Alembic commands ###
