"""add_operational_metrics_and_order_dates

Revision ID: e44fdd963639
Revises: 5673a58d564e
Create Date: 2025-12-12 07:05:13.860575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44fdd963639'
down_revision: Union[str, None] = '5673a58d564e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_analytics', sa.Column('avg_processing_time', sa.Float(), nullable=True))
    op.add_column('daily_analytics', sa.Column('avg_shipping_time', sa.Float(), nullable=True))
    op.add_column('daily_stats', sa.Column('avg_processing_time', sa.Float(), nullable=True))
    op.add_column('daily_stats', sa.Column('avg_shipping_time', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('shipped_date', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('tracking_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'tracking_id')
    op.drop_column('orders', 'shipped_date')
    op.drop_column('daily_stats', 'avg_shipping_time')
    op.drop_column('daily_stats', 'avg_processing_time')
    op.drop_column('daily_analytics', 'avg_shipping_time')
    op.drop_column('daily_analytics', 'avg_processing_time')
    # ### end Alembic commands ###
