"""rename_shipped_date_to_shipped_time

Revision ID: e484baad037e
Revises: e44fdd963639
Create Date: 2025-12-12 12:03:11.767121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e484baad037e'
down_revision: Union[str, None] = 'e44fdd963639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'shipped_date', new_column_name='shipped_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'shipped_time', new_column_name='shipped_date')
    # ### end Alembic commands ###
