"""add indexes for searching

Revision ID: e6eff32852da
Revises: ef45588364cf
Create Date: 2026-01-21 10:24:02.128806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6eff32852da'
down_revision: Union[str, None] = 'ef45588364cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_orders_order_date'), 'orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_orders_tracking_id'), 'orders', ['tracking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_tracking_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_date'), table_name='orders')
    # ### end Alembic commands ###
