"""drop_customers_table

Revision ID: ef45588364cf
Revises: 74ce022fd3b8
Create Date: 2026-01-18 09:47:44.007226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef45588364cf'
down_revision: Union[str, None] = '74ce022fd3b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_brand_id', table_name='customers')
    op.drop_index('ix_customers_city', table_name='customers')
    op.drop_index('ix_customers_district', table_name='customers')
    op.drop_index('ix_customers_id', table_name='customers')
    op.drop_index('ix_customers_source', table_name='customers')
    op.drop_index('ix_customers_username', table_name='customers')
    op.drop_table('customers')
    op.drop_index('ix_customer_order_analytics_brand_id', table_name='customer_order_analytics')
    op.drop_index('ix_customer_order_analytics_id', table_name='customer_order_analytics')
    op.drop_index('ix_customer_order_analytics_order_code', table_name='customer_order_analytics')
    op.drop_index('ix_customer_order_analytics_order_date', table_name='customer_order_analytics')
    op.drop_index('ix_customer_order_analytics_phone_number', table_name='customer_order_analytics')
    op.drop_index('ix_customer_order_analytics_source', table_name='customer_order_analytics')
    op.drop_index('ix_customer_order_analytics_status', table_name='customer_order_analytics')
    op.drop_index('ix_customer_order_analytics_tracking_id', table_name='customer_order_analytics')
    op.drop_index('ix_customer_order_analytics_username', table_name='customer_order_analytics')
    op.drop_table('customer_order_analytics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_order_analytics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tracking_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('order_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('shipping_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('product_summary', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_cancelled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_bomb', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_refunded', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('full_search_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name='customer_order_analytics_brand_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='customer_order_analytics_pkey'),
    sa.UniqueConstraint('brand_id', 'order_code', name='uq_analytics_order_code', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_customer_order_analytics_username', 'customer_order_analytics', ['username'], unique=False)
    op.create_index('ix_customer_order_analytics_tracking_id', 'customer_order_analytics', ['tracking_id'], unique=False)
    op.create_index('ix_customer_order_analytics_status', 'customer_order_analytics', ['status'], unique=False)
    op.create_index('ix_customer_order_analytics_source', 'customer_order_analytics', ['source'], unique=False)
    op.create_index('ix_customer_order_analytics_phone_number', 'customer_order_analytics', ['phone_number'], unique=False)
    op.create_index('ix_customer_order_analytics_order_date', 'customer_order_analytics', ['order_date'], unique=False)
    op.create_index('ix_customer_order_analytics_order_code', 'customer_order_analytics', ['order_code'], unique=False)
    op.create_index('ix_customer_order_analytics_id', 'customer_order_analytics', ['id'], unique=False)
    op.create_index('ix_customer_order_analytics_brand_id', 'customer_order_analytics', ['brand_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('district', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_spent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_orders', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_order_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('cancelled_orders', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bomb_orders', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('refunded_orders', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completed_orders', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name='customers_brand_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='customers_pkey')
    )
    op.create_index('ix_customers_username', 'customers', ['username'], unique=False)
    op.create_index('ix_customers_source', 'customers', ['source'], unique=False)
    op.create_index('ix_customers_id', 'customers', ['id'], unique=False)
    op.create_index('ix_customers_district', 'customers', ['district'], unique=False)
    op.create_index('ix_customers_city', 'customers', ['city'], unique=False)
    op.create_index('ix_customers_brand_id', 'customers', ['brand_id'], unique=False)
    # ### end Alembic commands ###
