"""add_new_returning_customers_to_dailystat

Revision ID: f1e7b13548a8
Revises: 16af294f87f4
Create Date: 2026-01-04 11:09:02.706066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e7b13548a8'
down_revision: Union[str, None] = '16af294f87f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_stats', sa.Column('new_customers', sa.Integer(), nullable=True))
    op.add_column('daily_stats', sa.Column('returning_customers', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_stats', 'returning_customers')
    op.drop_column('daily_stats', 'new_customers')
    # ### end Alembic commands ###
