"""add role to users table

Revision ID: f7fefea9934e
Revises: 1e27b894cd2b
Create Date: 2026-02-26 04:30:36.292313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7fefea9934e'
down_revision: Union[str, None] = '1e27b894cd2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_role = sa.Enum('ADMIN', 'MANAGER', 'VIEWER', name='userrole')
    user_role.create(op.get_bind())
    op.add_column('users', sa.Column('role', user_role, nullable=False, server_default='VIEWER'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    sa.Enum(name='userrole').drop(op.get_bind())
    # ### end Alembic commands ###
